---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-url-registry-access-{{ .Release.Namespace }}
  namespace: rhoai-model-registries
  annotations:
    argocd.argoproj.io/sync-wave: "110"
subjects:
  - kind: ServiceAccount
    name: cluster-url-getter-{{ .Release.Namespace }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: registry-user-predictive-lifecycle