apiVersion: v2
name: predictive-lifecycle
description: GitOps to set up a demo for the general  GitOps for obtaining the URL of your OpenShift cluster.

type: application

version: 0.1.0

appVersion: "1.0.0"

dependencies:
  - name: cluster-url-getter
    version: 0.1.0
    repository: "file://../../../helm/cluster-url-getter"
  - name: create-model-registry
    version: 0.0.4
    repository: https://redhat-ai-americas.github.io/create-model-registry
  - name: minio
    version: 0.1.0
    repository: "file://../../../helm/10-minio"
  - name: pipeline-server
    version: 0.1.0
    repository: "file://../../../helm/20-pipeline-server"
