apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-integration
  annotations:
    argocd.argoproj.io/sync-wave: "21"
data:
  create_secret.sh: |-
    {{ .Files.Get "files/create_secret.sh" | nindent 4 }}