apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    notebooks.opendatahub.io/inject-auth: 'true'
    opendatahub.io/image-display-name: {{ .Values.workbench.imageDisplayName }}
    opendatahub.io/accelerator-name: ''
    openshift.io/description: ''
    openshift.io/display-name: data-generation
    notebooks.opendatahub.io/last-image-version-git-commit-selection: d3137ca
    notebooks.opendatahub.io/last-image-selection: {{ .Values.workbench.image }}
    opendatahub.io/legacy-hardware-profile-name: small-notebooks-1bmle
    notebooks.opendatahub.io/last-size-selection: ''
    opendatahub.io/username: 'kube:admin'
    opendatahub.io/hardware-profile-name: ''
    argocd.argoproj.io/sync-wave: "110"
  name: data-generation
  namespace: {{ .Release.Namespace }}
  labels:
    app: data-generation
    opendatahub.io/dashboard: 'true'
    opendatahub.io/odh-managed: 'true'
    opendatahub.io/user: kube-3aadmin
spec:
  template:
    spec:
      initContainers:
        - name: copy-resources
          image: registry.access.redhat.com/ubi9/python-312  # This is effectively required due to folder existence issues on other UBIs.
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args:
            - -ec
            - |-
              if [ ! -d /opt/app-root/src/scripts ] || [ -z $( ls -A /opt/app-root/src/scripts/ ) ]; then cp -R /scripts /opt/app-root/src/; fi
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: data-generation-storage
              mountPath: /opt/app-root/src/
      containers:
        - resources:
            limits:
              cpu: '1'
              memory: 8Gi
            requests:
              cpu: '1'
              memory: 8Gi
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /notebook/{{ .Release.Namespace }}/data-generation/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: data-generation
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /notebook/{{ .Release.Namespace }}/data-generation/api
              port: notebook-port
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: NOTEBOOK_ARGS
              value: |-
                --ServerApp.port=8888
                                  --ServerApp.token=''
                                  --ServerApp.password=''
                                  --ServerApp.base_url=/notebook/{{ .Release.Namespace }}/data-generation
                                  --ServerApp.quit_button=False
            - name: JUPYTER_IMAGE
              value: 'image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/{{ .Values.workbench.image }}'
            - name: PIP_CERT
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: REQUESTS_CA_BUNDLE
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: SSL_CERT_FILE
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: PIPELINES_SSL_SA_CERTS
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
            - name: GIT_SSL_CAINFO
              value: /etc/pki/tls/custom-certs/ca-bundle.crt
          envFrom:
            - secretRef:
                name: postgres-creds
          ports:
            - containerPort: 8888
              name: notebook-port
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /opt/app-root/src/
              name: data-generation-storage
            - mountPath: /dev/shm
              name: shm
            - mountPath: /etc/pki/tls/custom-certs/ca-bundle.crt
              name: trusted-ca
              readOnly: true
              subPath: ca-bundle.crt
            - mountPath: /opt/app-root/pipeline-runtimes/
              name: runtime-images
            - mountPath: /opt/app-root/runtimes
              name: elyra-dsp-details
          image: 'image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/{{ .Values.workbench.image }}'
          workingDir: /opt/app-root/src
        - resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8444
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: kube-rbac-proxy
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8444
              scheme: HTTPS
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          ports:
            - containerPort: 8443
              name: kube-rbac-proxy
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /etc/kube-rbac-proxy
              name: kube-rbac-proxy-config
            - mountPath: /etc/tls/private
              name: kube-rbac-proxy-tls-certificates
          image: 'registry.redhat.io/rhoai/odh-kube-auth-proxy-rhel9@sha256:1f4b2b9bb5061faf17299c2ae2405ab408e2b7ce349d9831eb6045990e6da005'
          args:
            - '--secure-listen-address=0.0.0.0:8443'
            - '--upstream=http://127.0.0.1:8888/'
            - '--logtostderr=true'
            - '--v=10'
            - '--proxy-endpoints-port=8444'
            - '--config-file=/etc/kube-rbac-proxy/config-file.yaml'
            - '--tls-cert-file=/etc/tls/private/tls.crt'
            - '--tls-private-key-file=/etc/tls/private/tls.key'
            - '--auth-header-fields-enabled=true'
            - '--auth-header-user-field-name=X-Auth-Request-User'
            - '--auth-header-groups-field-name=X-Auth-Request-Groups'
      enableServiceLinks: false
      serviceAccountName: data-generation
      volumes:
        - name: data-generation-storage
          persistentVolumeClaim:
            claimName: data-generation-storage
        - emptyDir:
            medium: Memory
          name: shm
        - configMap:
            items:
              - key: ca-bundle.crt
                path: ca-bundle.crt
            name: workbench-trusted-ca-bundle
            optional: true
          name: trusted-ca
        - configMap:
            name: pipeline-runtime-images
            optional: true
          name: runtime-images
        - name: elyra-dsp-details
          secret:
            optional: true
            secretName: ds-pipeline-config
        - name: kube-rbac-proxy-config
          configMap:
            defaultMode: 420
            name: data-generation-kube-rbac-proxy-config
        - name: kube-rbac-proxy-tls
          secret:
            defaultMode: 420
            secretName: data-generation-kube-rbac-proxy-tls
        - name: scripts
          configMap:
            name: data-generation-scripts
            defaultMode: 0755
