kind: ServiceAccount
apiVersion: v1
metadata:
  name: test-with-sa
  namespace: {{ .Release.Namespace }}
  labels:
    notebook-name: test-with-sa
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: data-generation
  namespace: {{ .Release.Namespace }}
  labels:
    notebook-name: test-with-sa